'\" t
.\"     Title: archlinux
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/21/2017
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ARCHLINUX" "7" "05/21/2017" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
archlinux \- basic configuration
.SH "SYNOPSIS"
.sp
Overview of the basic configuration of Arch Linux\&.
.SH "DESCRIPTION"
.sp
Arch Linux exposes the user to the system without hiding any details\&. This man page gives a brief overview of the configuration files that should be set up on a fresh install\&.
.SH "SYSTEM SERVICES"
.sp
System services to be started at boot can be enabled using \fIsystemctl enable <name>\fR\&. To view available services, use \fIsystemctl list\-unit\-files\fR\&.
.SH "HOSTNAME"
.sp
The hostname of the machine can be set using \fIhostnamectl set\-hostname <hostname>\fR\&. It will then be written to /etc/hostname\&.
.SH "LOCALIZATION"
.sp
Various locales may be enabled in /etc/locale\&.gen and are generated by \fIlocale\-gen\fR\&. The system\-wide locale to be used can be configured in /etc/locale\&.conf\&. These settings can be overridden on a per\-user basis by keeping a user\-specific locale\&.conf in $HOME/\&.config/locale\&.conf\&. The user\-specific file will take precedence if it exists\&.
.SH "VIRTUAL CONSOLE"
.sp
The virtual console is configured in /etc/vconsole\&.conf\&. It allows you to set a font and a keyboard layout, among other things\&. Note that these settings only apply to the console and do not apply if you use X\&.
.SH "TIME"
.sp
The local time zone is configured by calling \fItimedatectl set\-timezone <Region/City>\fR\&. A relative \fBsymlink\fR is then created from /etc/localtime to the correct zoneinfo file under /usr/share/zoneinfo/\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
/etc/localtime \-> \&.\&./usr/share/zoneinfo/Europe/Paris
.fi
.if n \{\
.RE
.\}
.sp
The real\-time clock, which keeps track of time when the computer is off, can be configured to either be in UTC or in local time by calling \fItimedatectl set\-local\-rtc <false|true>\fR\&. The default is UTC\&.
.SH "FILE SYSTEMS"
.sp
File systems are configured in /etc/fstab, and encryption mappings are configured in /etc/crypttab\&.
.SH "INITRAMFS"
.sp
The initramfs is generated by \fImkinitcpio \-p <preset>\fR\&. The default preset is "linux"\&. The initramfs can be configured in /etc/mkinitcpio\&.conf and must be regenerated after making configuration changes\&.
.SH "PACKAGE MANAGER"
.sp
The package manager, pacman, is configured in /etc/pacman\&.conf\&.
.SH "BOOT LOADER"
.sp
GRUB\(cqs configuration is generated from /etc/default/grub by \fIgrub\-mkconfig \-o /boot/grub/grub\&.cfg\fR\&. Syslinux is configured in /boot/syslinux/syslinux\&.cfg\&.
.SH "MODULES"
.sp
Most modules should be loaded on\-demand\&. Modules to be unconditionally loaded at boot can be specified in /etc/modules\-load\&.d/, and modules to be blacklisted from automatically loading can be configured in /etc/modprobe\&.d/\&.
.SH "SEE ALSO"
.sp
\fBsystemctl\fR(1), \fBhostnamectl\fR(1), \fBhostname\fR(5), \fBlocale\&.conf\fR(5), \fBvconsole\&.conf\fR(5), \fBtimedatectl\fR(1), \fBtimezone\fR(3), \fBhwclock\fR(8), \fBfstab\fR(5), \fBcrypttab\fR(5), \fBmkinitcpio\fR(8), \fBpacman\fR(8), \fBpacman\&.conf\fR(5), \fBgrub\-mkconfig\fR(8), \fBsyslinux\fR(1), \fBmodules\-load\&.d\fR(5), \fBmodprobe\&.d\fR(5), \fBsystemd\fR(1)
.SH "AUTHORS"
.sp
Written by Tom Gundersen\&.
